# Generated by Django 5.0.7 on 2024-08-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_name', models.CharField(max_length=50, unique=True)),
                ('data_email', models.EmailField(max_length=254, unique=True)),
                ('data_phone_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
